---
version: '3.8'

services:
  prod:
    build: 
      context: .
      target: prod
    image: pedrotroller/http-markup

  dev:
    build: 
      context: .
      target: dev
    volumes:
      - '.:/var/www/html/'
